/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion;

/**
 *
 * @author 233215 y 
 */
public class ActualizaSaldo extends javax.swing.JDialog {

    /**
     * Creates new form ActualizaSaldo
     */
    public ActualizaSaldo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textActualizarSaldo = new javax.swing.JLabel();
        botonAñadir = new javax.swing.JButton();
        botonRestar = new javax.swing.JButton();
        textEligeCuenta = new javax.swing.JLabel();
        textIngreseCantidad = new javax.swing.JLabel();
        jtextoCantidad = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textActualizarSaldo.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        textActualizarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        textActualizarSaldo.setText("Actualizar Saldo");
        jPanel1.add(textActualizarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        botonAñadir.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        botonAñadir.setText("Añadir");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(botonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 80, -1));

        botonRestar.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        botonRestar.setText("Restar");
        botonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        textEligeCuenta.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        textEligeCuenta.setForeground(new java.awt.Color(255, 255, 255));
        textEligeCuenta.setText("Elige Cuenta:");
        jPanel1.add(textEligeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        textIngreseCantidad.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        textIngreseCantidad.setForeground(new java.awt.Color(255, 255, 255));
        textIngreseCantidad.setText("Ingrese cantidad:");
        jPanel1.add(textIngreseCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jtextoCantidad.setMaximumSize(new java.awt.Dimension(10, 2));
        jtextoCantidad.setMinimumSize(new java.awt.Dimension(10, 10));
        jtextoCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextoCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(jtextoCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 200, 30));

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAñadirActionPerformed

    private void botonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRestarActionPerformed

    private void jtextoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextoCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextoCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizaSaldo dialog = new ActualizaSaldo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonRestar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtextoCantidad;
    private javax.swing.JLabel textActualizarSaldo;
    private javax.swing.JLabel textEligeCuenta;
    private javax.swing.JLabel textIngreseCantidad;
    // End of variables declaration//GEN-END:variables
}
