
package presentacion;

/**
 *
 * @author 233215 y 
 */
public class CuentaCliente extends javax.swing.JFrame {

    /**
     * Creates new form CuentaCliente
     */
    public CuentaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textCrearCuenta = new javax.swing.JLabel();
        botonTransferir = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        textIdCuenta = new javax.swing.JLabel();
        textSaldo = new javax.swing.JLabel();
        textFechaA = new javax.swing.JLabel();
        jtextoIdCuenta = new javax.swing.JTextField();
        jtextoSaldo = new javax.swing.JTextField();
        jtextoFechaA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textCrearCuenta.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        textCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        textCrearCuenta.setText("Datos Cuenta ");
        jPanel1.add(textCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        botonTransferir.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        botonTransferir.setText("Transferir");
        botonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTransferirActionPerformed(evt);
            }
        });
        jPanel1.add(botonTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 100, -1));

        botonRegresar.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        textIdCuenta.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        textIdCuenta.setForeground(new java.awt.Color(255, 255, 255));
        textIdCuenta.setText("ID Cuenta:");
        jPanel1.add(textIdCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        textSaldo.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        textSaldo.setForeground(new java.awt.Color(255, 255, 255));
        textSaldo.setText("Saldo:");
        jPanel1.add(textSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        textFechaA.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        textFechaA.setForeground(new java.awt.Color(255, 255, 255));
        textFechaA.setText("Fecha apertura:");
        jPanel1.add(textFechaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jtextoIdCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextoIdCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(jtextoIdCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 240, 30));

        jtextoSaldo.setMaximumSize(new java.awt.Dimension(10, 2));
        jtextoSaldo.setMinimumSize(new java.awt.Dimension(10, 10));
        jtextoSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextoSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(jtextoSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 240, 30));

        jtextoFechaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextoFechaAActionPerformed(evt);
            }
        });
        jPanel1.add(jtextoFechaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTransferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTransferirActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void jtextoIdCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextoIdCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextoIdCuentaActionPerformed

    private void jtextoSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextoSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextoSaldoActionPerformed

    private void jtextoFechaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextoFechaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextoFechaAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuentaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuentaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuentaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuentaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuentaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonTransferir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtextoFechaA;
    private javax.swing.JTextField jtextoIdCuenta;
    private javax.swing.JTextField jtextoSaldo;
    private javax.swing.JLabel textCrearCuenta;
    private javax.swing.JLabel textFechaA;
    private javax.swing.JLabel textIdCuenta;
    private javax.swing.JLabel textSaldo;
    // End of variables declaration//GEN-END:variables
}
