/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author juanc
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textIniciarS = new javax.swing.JLabel();
        textIngresar = new javax.swing.JLabel();
        jtextoIngresarNumeroCuenta = new javax.swing.JTextField();
        botonIngresar = new javax.swing.JButton();
        botonRetiroSC = new javax.swing.JButton();
        botonCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textIniciarS.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        textIniciarS.setForeground(new java.awt.Color(255, 255, 255));
        textIniciarS.setText("Inicio de sesion");
        jPanel1.add(textIniciarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        textIngresar.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        textIngresar.setForeground(new java.awt.Color(255, 255, 255));
        textIngresar.setText("Numero de cuenta:");
        jPanel1.add(textIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jtextoIngresarNumeroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextoIngresarNumeroCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(jtextoIngresarNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 240, 30));

        botonIngresar.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 80, -1));

        botonRetiroSC.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        botonRetiroSC.setText("Retiro sin cuenta");
        botonRetiroSC.setToolTipText("");
        jPanel1.add(botonRetiroSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        botonCrearCuenta.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        botonCrearCuenta.setText("Crear cuenta");
        botonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextoIngresarNumeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextoIngresarNumeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextoIngresarNumeroCuentaActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearCuenta;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonRetiroSC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtextoIngresarNumeroCuenta;
    private javax.swing.JLabel textIngresar;
    private javax.swing.JLabel textIniciarS;
    // End of variables declaration//GEN-END:variables
}
