/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author 233215 y 233301
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textRetiroSC = new javax.swing.JLabel();
        textBienvenido = new javax.swing.JLabel();
        botonCrearCuenta = new javax.swing.JButton();
        botonRetiroSC = new javax.swing.JButton();
        botonCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textRetiroSC.setFont(new java.awt.Font("Arial Narrow", 1, 28)); // NOI18N
        textRetiroSC.setForeground(new java.awt.Color(255, 255, 255));
        textRetiroSC.setText("Seleccione opcion");
        jPanel1.add(textRetiroSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        textBienvenido.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        textBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        textBienvenido.setText("Bienvenido a BBDAV");
        jPanel1.add(textBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        botonCrearCuenta.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        botonCrearCuenta.setText("Crear Cuenta");
        botonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 160, 40));

        botonRetiroSC.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        botonRetiroSC.setText("Retiro Sin Cuenta");
        botonRetiroSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetiroSCActionPerformed(evt);
            }
        });
        jPanel1.add(botonRetiroSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 170, 40));

        botonCliente.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        botonCliente.setText("Cliente");
        botonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteActionPerformed(evt);
            }
        });
        jPanel1.add(botonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuentaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonCrearCuentaActionPerformed

    private void botonRetiroSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetiroSCActionPerformed
        // TODO add your handling code here:
        RetiroForm retiro = new RetiroForm();
        retiro.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRetiroSCActionPerformed

    private void botonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteActionPerformed
        // TODO add your handling code here:
        InicioSesion inicio = new InicioSesion();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCliente;
    private javax.swing.JButton botonCrearCuenta;
    private javax.swing.JButton botonRetiroSC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textBienvenido;
    private javax.swing.JLabel textRetiroSC;
    // End of variables declaration//GEN-END:variables
}
