/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author 233215 y 233301
 */
public class RetiroForm extends javax.swing.JFrame {

    /**
     * Creates new form RetiroSC
     */
    public RetiroForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textIngresar1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textRetiroSC = new javax.swing.JLabel();
        textIngresar = new javax.swing.JLabel();
        jtextoIngresarNumeroCuenta = new javax.swing.JTextField();
        botonIngresar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtextoContraseña = new javax.swing.JTextField();

        textIngresar1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        textIngresar1.setForeground(new java.awt.Color(255, 255, 255));
        textIngresar1.setText("Ingrese Folio:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textRetiroSC.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        textRetiroSC.setForeground(new java.awt.Color(255, 255, 255));
        textRetiroSC.setText("Retiro sin cuenta");
        jPanel1.add(textRetiroSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        textIngresar.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        textIngresar.setForeground(new java.awt.Color(255, 255, 255));
        textIngresar.setText("Folio:");
        jPanel1.add(textIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jtextoIngresarNumeroCuenta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtextoIngresarNumeroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextoIngresarNumeroCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(jtextoIngresarNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 240, 30));

        botonIngresar.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 80, -1));

        botonRegresar.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jtextoContraseña.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jPanel1.add(jtextoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void jtextoIngresarNumeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextoIngresarNumeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextoIngresarNumeroCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtextoContraseña;
    private javax.swing.JTextField jtextoIngresarNumeroCuenta;
    private javax.swing.JLabel textIngresar;
    private javax.swing.JLabel textIngresar1;
    private javax.swing.JLabel textRetiroSC;
    // End of variables declaration//GEN-END:variables
}
