/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import dominio.Transferencia;
import excepciones.PersistenciaException;
import implementaciones.TransferenciasDAO;
import interfaces.ITransferenciasDAO;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 233215 y 233301
 */
public class TransferenciaForm extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(TransferenciasDAO.class.getName());
    
    ITransferenciasDAO transferenciasDAO;
    
    /**
     * Creates new form Transferencia
     */
    public TransferenciaForm() {
        initComponents();
        setLocationRelativeTo(null);
        transferenciasDAO=null;
    }

    private void confirmarTransferencia(Transferencia transf){
        try{
            transferenciasDAO.transferir(transf);
        } catch(PersistenciaException e){
            LOG.log(Level.SEVERE, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textRetiroSC = new javax.swing.JLabel();
        textIngresar = new javax.swing.JLabel();
        botonEnviar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfCantidad = new javax.swing.JTextField();
        txfCuentaReceptora = new javax.swing.JTextField();
        txfCuentaEmisora = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textRetiroSC.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        textRetiroSC.setForeground(new java.awt.Color(255, 255, 255));
        textRetiroSC.setText("Transferencia");
        jPanel1.add(textRetiroSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        textIngresar.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        textIngresar.setForeground(new java.awt.Color(255, 255, 255));
        textIngresar.setText("Cuenta Emisora");
        jPanel1.add(textIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        botonEnviar.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        botonEnviar.setText("Enviar");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 80, -1));

        botonRegresar.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cuenta Receptora");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel1.add(txfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 200, 30));

        txfCuentaReceptora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCuentaReceptoraActionPerformed(evt);
            }
        });
        jPanel1.add(txfCuentaReceptora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 190, -1));
        jPanel1.add(txfCuentaEmisora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        // TODO add your handling code here:
        float cantidad = Float.parseFloat(txfCantidad.getText());
        int idEmisor = Integer.parseInt(txfCuentaEmisora.getText());
        int idDestino = Integer.parseInt(txfCuentaReceptora.getText());
        
        Transferencia transf = new Transferencia(idEmisor, idDestino, cantidad);
        
        this.confirmarTransferencia(transf);
        
    }//GEN-LAST:event_botonEnviarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void txfCuentaReceptoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCuentaReceptoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCuentaReceptoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferenciaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferenciaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferenciaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferenciaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferenciaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textIngresar;
    private javax.swing.JLabel textRetiroSC;
    private javax.swing.JTextField txfCantidad;
    private javax.swing.JTextField txfCuentaEmisora;
    private javax.swing.JTextField txfCuentaReceptora;
    // End of variables declaration//GEN-END:variables
}
